import Link from 'next/link';
import './globals.css';
import { Inter } from 'next/font/google';
import Image from 'next/image';
import favicon from './favicon.ico';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex justify-center items-center flex-col min-h-screen text-gray-600 text-sm font-mono`}
      >
        <header>
          <nav className="bg-gray-800 w-screen">
            <div className="flex items-center pl-8 h-14">
              <div className="flex space-x-4">
                <Link
                  href="/"
                  className="text-gray-300 hover:bg-gray-700 px-3 py-2 rounded"
                >
                  Home
                </Link>
                <Link
                  href="/blog-page"
                  className="text-gray-300 hover:bg-gray-700 px-3 py-2 rounded"
                >
                  Blog
                </Link>
                <Link
                  href="/contact-page"
                  className="text-gray-300 hover:bg-gray-700 px-3 py-2 rounded"
                >
                  Contact
                </Link>
              </div>
            </div>
          </nav>
        </header>
        <main className="flex flex-1 justify-center items-center flex-col w-screen">
          {children}
        </main>
        <footer className="w-full h-12 border-t text-center">
          <div className="flex justify-center items-center py-3">
            <p>©Tai Takahashi &nbsp; Powerd By</p>
            <Image src={favicon} alt="vercel logo" className="ml-1" />
          </div>
          <p style={{ fontSize: '10px' }}>
            Image from{' '}
            <a href="https://www.vecteezy.com/free-vector/avatar">
              Avatar Vectors by Vecteezy
            </a>
            ,{' '}
            <a target="_blank" href="https://icons8.com/icon">
              Twitter Facebook Github
            </a>{' '}
            icon by{' '}
            <a target="_blank" href="https://icons8.com">
              Icons8
            </a>
          </p>
        </footer>
      </body>
    </html>
  );
}
